SmartSchool/SmartSchool/Controllers/CommunicateController.cs
using SmartSchool.Interfaces;
using SmartSchool.Models;
using SmartSchool.SchoolMasterClasses;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web.Mvc;

namespace SmartSchool.Controllers

{
    public class CommunicateController : Controller
    {
        private readonly ISessionStore _UsesessionStore;
        public SmartSchoolHDEntities dbContext = new SmartSchoolHDEntities();
        public custom_master_class cmc = new custom_master_class();
        public SmsTextLocalClass stl = new SmsTextLocalClass();
        public get_session_data1 listData;
        public CommunicateController(ISessionStore _GetsessionStore)
        {
            try
            {
                _UsesessionStore = _GetsessionStore;
                listData = _UsesessionStore.Get<get_session_data1>("currentSession") as get_session_data1;
                if (listData == null)
                {
                    throw new Exception("Session not been set in CommunicateController");
                }
            }
            catch (Exception ex)
            {
                ExceptionLogging.LogException(ex);
            }
        }
     
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult notice_board()
        {
            IQueryable<send_notification> isn = dbContext.send_notification;
            ViewBag.isn = (from isnval in isn where isnval.college_id == listData.CollegeID && isnval.branch_id == listData.BranchID && isnval.year == listData.academic_year && isnval.is_active != false select isnval).ToList();
            return View();
        }

        [HttpGet]
        public ActionResult notice_board_delete(int? id, string edit)
        {
            notice_board();
            if (edit == null)
            {
                int c = 0;
                using (var ctx = new SmartSchoolHDEntities())
                {
                    var x = (from y in ctx.send_notification
                             where y.id == id && y.year == listData.academic_year
                             select y).FirstOrDefault();
                    if (x != null)
                    {
                        x.modified_by = listData.user;
                        x.updated_at = DateTime.Now;
                        ctx.SaveChanges();
                        ctx.send_notification.Remove(x);
                        c = ctx.SaveChanges();
                    }
                    if (c > 0)
                    {
                        TempData["message"] = "Record Deleted Successfully..!";
                        TempData.Keep();
                    }
                }
                return RedirectToAction("notice_board");
            }
            else
            {
                send_notification sn = dbContext.send_notification.Single(k => k.id == id);
                return View("send_message", sn);
            }
        }

        public ActionResult post_new_message()
        {
            return View();
        }

        [HttpGet]     
        public ActionResult send_message()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult save_send_message(string[] get_checkedval, string content, string email_subject, send_notification model, string publish_date, string notice_date, int? notification_id)
        {
            int c = 0;
            if (notification_id == 0 || notification_id == null)
            {
                send_notification el = new send_notification()
                {
                    college_id = listData.CollegeID,
                    branch_id = listData.BranchID,
                    created_at = DateTime.Now,
                    title = email_subject,
                    date = Convert.ToDateTime(notice_date),
                    publish_date = Convert.ToDateTime(publish_date),
                    message = content,
                    created_by = listData.user,
                    is_active = true,
                    created_id = 2015,
                    visible_parent = false,
                    visible_staff = false,
                    visible_student = false,
                    year = listData.academic_year
                };
                foreach (var citems in get_checkedval)
                {
                    if (citems == "Student")
                    {
                        el.visible_student = true;
                    }
                    else if (citems == "Parent")
                    {
                        el.visible_parent = true;
                    }
                    else if (citems == "Staff")
                    {
                        el.visible_staff = true;
                    }
                }
                dbContext.send_notification.Add(el);
                c = dbContext.SaveChanges();
            }

            else
            {
                IQueryable<send_notification> isn = dbContext.send_notification;
                var result = isn.SingleOrDefault(b => b.id == notification_id);
                if (result != null)
                {
                    result.title = email_subject;
                    result.publish_date = Convert.ToDateTime(publish_date);
                    result.date = Convert.ToDateTime(notice_date);
                    result.message = content;
                    foreach (var citems in get_checkedval)
                    {
                        if (citems == "Student")
                        {
                            result.visible_student = true;
                        }
                        else if (citems == "Parent")
                        {
                            result.visible_parent = true;
                        }
                        else if (citems == "Staff")
                        {
                            result.visible_staff = true;
                        }
                    }
                    c = dbContext.SaveChanges();
                }
            }
            if (c > 0)
            {
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("Fail", JsonRequestBehavior.AllowGet);
            }
        }


        public class getcharge
        {
            public int? id { get; set; }
            public string message { get; set; }
            public string Code { get; set; }
        }

        public JsonResult GetCharge(int id)
        {
            var mes = dbContext.send_notification.Where(x => x.id == id ).Select(a => a.message).FirstOrDefault();
            return Json(mes, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [ValidateInput(false)]
        public ActionResult send_email_sms()
        {
           // ViewBag.classes = dbContext.AddClasses.Where(k => k.college_id == listData.CollegeID && k.branch_id == listData.BranchID && k.year == listData.academic_year).ToList();
            ViewBag.list = new SelectList(dbContext.send_notification, "id", "title", "0");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult send_email_sms(send_notification model, string[] get_checkedval, string content, string[] get_id, string[] dropdwn, string[] multi_select, string email_subject, string[] get_id_sms, string activetab)
        {
            IQueryable<string> staffs = dbContext.AspNetRoles.Where(k => k.Name != "Student" && k.Name != "Parent").Select(k => k.Name);
            string user = null;
            dynamic return_val = null;
            if (get_checkedval != null)
            {
                foreach (var citems in get_checkedval)
                {
                    if (staffs.Contains(citems))
                    {
                        user = "Staff";
                    }
                    switch (user == "Staff" ? "Staff" : citems)
                    {
                        case "Student":
                            var allstudents = cmc.get_all_student(listData.CollegeID, listData.BranchID, listData.academic_year, null, null);
                            foreach (var als in allstudents)
                            {
                                if (als.Count != 0)
                                {
                                    foreach (var alsl in als)
                                    {
                                        return_val = cmc.send_mail(alsl.Email, email_subject, content);
                                        TempData["Students"] += alsl.AdmissionNumber + ",";
                                        return_val = return_val == false ? false : true;
                                        if (return_val == false)
                                        {
                                            break;
                                        }
                                    }
                                    if (return_val == true)
                                    {
                                        return_val = "Email Sent Successfully..!";
                                        save_data_tomessages_table(email_subject, content, TempData["Students"], activetab);
                                        TempData.Remove("Students");
                                    }
                                }
                                else
                                {
                                    return_val = "No Students Found";
                                }
                            }
                            break;

                        case "Parent":
                            var allparent = cmc.get_all_parent(listData.CollegeID, listData.BranchID, listData.academic_year, null, null);
                            foreach (var alsp in allparent)
                            {

SmartSchool/SmartSchool/Views/Communicate/notice_board.cshtml
@model SmartSchool.Models.send_notification
@{
    ViewBag.Title = "notice_board";
    Layout = "~/Views/Admin/Shared/_AdminLayoutPage.cshtml";
}


@*<button type="button" class="btn btn-default btn-outline" data-toggle="tooltip" data-placement="top" title="" data-original-title="Tooltip on top">Tooltip on top</button>*@

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h4 style="color:#f742aa;">@SmartSchool.Resources.Resource1.Communicate</h4>
                </div>
                <div class="pull-right">
                    <input type="submit" class="btn btn-info zmdi-text-format" id="pnmessage" value="@SmartSchool.Resources.Resource1.Send_Message" formtarget="_blank" onclick="window.open('@Url.Action("send_message", "Communicate")')" />
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm("notice_board", "Communicate", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default card-view">
        <div class="panel-wrapper collapse in">
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <div class="form-body">
                            <h6 class="txt-dark capitalize-font"><i class="zmdi zmdi-notifications mr-10"></i>@SmartSchool.Resources.Resource1.Notice_Board</h6>
                            <hr class="light-grey-hr" />
                            @foreach (var items in ViewBag.isn)
                            {
                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <div class="panel panel-default card-view panel-refresh">
                                        <div class="refresh-container">
                                            <div class="la-anim-1"></div>
                                        </div>
                                        <div class="panel-heading">
                                            <div class="pull-left">
                                                <small class="font-13">
                                                    <i class="fa fa-info-circle" style="color:deeppink"></i> <text style="color:black"> @items.title</text>
                                                </small>
                                                @*<small class="panel-title txt-dark">@items.title</small>*@
                                            </div>
                                            <div class="pull-right">
                                                <a class="pull-left inline-block mr-15" data-toggle="collapse"  href="#collapse_@items.id" aria-expanded="false">
                                                    <i class="zmdi zmdi-chevron-down" style="color:#f742aa"></i>
                                                    <i class="zmdi zmdi-chevron-up" style="color:#f742aa"></i>
                                                </a>
                                                <a href="#" class="pull-left inline-block full-screen mr-15">
                                                    <i class="zmdi zmdi-fullscreen" data-toggle="tooltip" data-placement="top" style="color:#f742aa" data-original-title="Expand Message"></i>
                                                </a>
                                                @*<a class="pull-left inline-block close-panel" href="@Url.actio("notice_boardss", "Communicate", new { id = items.id })" data-effect="fadeOut">
                                                        <i class="zmdi zmdi-close"></i>
                                                    </a>*@

                                                @Html.ActionLink(" ", "notice_board_delete", new { edit = "edit", id = items.id }, new { @class = "pull-left inline-block close-panel zmdi zmdi-edit", title="Edit Message", style="Color:#f742aa"  })

                                                @Html.ActionLink(" ", "notice_board_delete", new { id = items.id }, new { @class = "pull-left inline-block close-panel zmdi zmdi-close", title="Delete Message", style="Color:#f742aa" })
                                            </div>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div id="collapse_@items.id" class="panel-wrapper collapse">
                                            <div class="panel-body font-16 weight-600 txt-dark">
                                                <p>@items.message</p> <br />
                                                @*<h6 class="txt-dark capitalize-font"><i class="zmdi zmdi-notifications mr-10"></i>Notice Board</h6>*@
                                                                      <small class="font-13"><i class="fa fa-calendar" style="color:deeppink"></i> @SmartSchool.Resources.Resource1.Publish_Date : @Convert.ToString(string.Format("{0:dd/MM/yyyy}", items.publish_date))</small><br />
                                                                      <small class="font-13"><i class="fa fa-calendar" style="color:deeppink"></i> @SmartSchool.Resources.Resource1.Notice_Date  : @Convert.ToString(string.Format("{0:dd/MM/yyyy}", items.date))</small><br />
                                                <small class="font-13">
                                                    <i class="fa fa-user-md" style="color:deeppink"></i> @SmartSchool.Resources.Resource1.Created_By        : @items.created_by
                                                </small><br />

                                                        <small class="font-15">
                                                            <i class="fa fa-info" style="color:cyan"></i> @SmartSchool.Resources.Resource1.Message_Displaying_To  :
                                                        </small><br />

                                                @if (items.visible_student == true)
                                                {
                                                      <small class="font-13">
                                                         <i class="fa fa-user" style="color:deeppink"></i> @SmartSchool.Resources.Resource1.Student
                                                      </small><br />
                                                }
                                                @if (items.visible_staff == true)
                                                {
                                                      <small class="font-13">
                                                          <i class="fa fa-user" style="color:deeppink"></i> @SmartSchool.Resources.Resource1.Staff
                                                      </small><br />
                                                }
                                                @if (items.visible_parent == true)
                                                {
                                                      <small class="font-13">
                                                          <i class="fa fa-user" style="color:deeppink"></i> @SmartSchool.Resources.Resource1.Parent
                                                      </small>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

SmartSchool/SmartSchool/Views/Communicate/post_new_message.cshtml
@model SmartSchool.Models.send_notification

@{
    ViewBag.Title = "post_new_message";
    Layout = "~/Views/Admin/Shared/_AdminLayoutPage.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h4 style="color:#f742aa; ">@SmartSchool.Resources.Resource1.Communicate</h4>
                </div>
                @*<div class="pull-right">
                        <input type="button" class="btn btn-info" value="Let's Go!" onclick="location.href='@Url.Action("Action", "Admin")'" />
                    </div>*@
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>




@using SmartSchool.Models;
@using SmartSchool.Interfaces;
@using SmartSchool.SchoolMasterClasses;
@{
    ISessionStore sessionStore = new SessionClass();
    get_session_data1 listData = sessionStore.Get<get_session_data1>("currentSession") as get_session_data1;
    ModulesAccess mm = new ModulesAccess();
    SmartSchoolHDEntities dbcontext = new SmartSchoolHDEntities();

    var getrolesacc = mm.RoleAccess(listData.roleid, 1, 1, listData.CollegeID, listData.BranchID);
    if (getrolesacc != null)
    {
        foreach (var rol in getrolesacc)
        {

            using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="panel panel-default card-view">
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-12 col-xs-12">
                                    <div class="form-wrap">
                                        <div class="form-body">
                                            <h6 class="txt-dark capitalize-font">
                                                <i class="zmdi zmdi-notifications mr-10"></i>@SmartSchool.Resources.Resource1.Notifications___Compose_New_Message
                                            </h6>
                                            <hr class="light-grey-hr" />
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-4" })
                                                        <div class="col-md-10">
                                                            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        @Html.Label(@SmartSchool.Resources.Resource1.Notice_Date, htmlAttributes: new { @class = "control-label col-md-4" })
                                                        <div class="col-md-10">
                                                            <input type="date" id="date" name="date" class="form-control col-md-4" />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        @Html.Label(@SmartSchool.Resources.Resource1.Publish_Date, htmlAttributes: new { @class = "control-label col-md-4" })
                                                        <div class="col-md-10">
                                                            <input type="date" id="date" name="date" class="form-control col-md-4" />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <br />
                                            <div class="row">
                                                <div class="col-md-8">
                                                    <div class="form-group">
                                                        @Html.LabelFor(model => model.message, htmlAttributes: new { @class = "control-label col-md-4" })
                                                        <div class="col-md-10">
                                                            <textarea class="tinymce"></textarea>

                                                        </div>
                                                    </div>
                                                </div>
                                                @Html.Label(@SmartSchool.Resources.Resource1.Message_To, htmlAttributes: new { @class = "control-label col-md-4" })
                                                <div class="col-md-3">

                                                    <div class="panel panel-default card-view">
                                                        <div class="form-group">
                                                            <div class="panel-body">
                                                                <p class="text-muted">@SmartSchool.Resources.Resource1.Select_Recipient </p>
                                                                <div class="row mt-40">
                                                                    <div class="col-sm-12">
                                                                        <div class="checkbox checkbox-info checkbox-circle">
                                                                            <input id="checkbox7" type="checkbox">
                                                                            <label for="checkbox7"> @SmartSchool.Resources.Resource1.Student </label>
                                                                        </div>
                                                                        <div class="checkbox checkbox-info checkbox-circle">
                                                                            <input id="checkbox8" type="checkbox">
                                                                            <label for="checkbox8"> @SmartSchool.Resources.Resource1.Parent </label>
                                                                        </div>
                                                                        <div class="checkbox checkbox-info checkbox-circle">
                                                                            <input id="checkbox-9" type="checkbox">
                                                                            <label for="checkbox-9"> @SmartSchool.Resources.Resource1.Teacher </label>
                                                                        </div>
                                                                        <div class="checkbox checkbox-info checkbox-circle">
                                                                            <input id="checkbox-10" type="checkbox">
                                                                            <label for="checkbox-10"> @SmartSchool.Resources.Resource1.Accountant </label>
                                                                        </div>
                                                                        <div class="checkbox checkbox-info checkbox-circle">
                                                                            <input id="checkbox-11" type="checkbox">
                                                                            <label for="checkbox-11"> @SmartSchool.Resources.Resource1.Librarian </label>
                                                                        </div>
                                                                        <div class="checkbox checkbox-info checkbox-circle">
                                                                            <input id="checkbox-12" type="checkbox">
                                                                            <label for="checkbox-12"> @SmartSchool.Resources.Resource1.Receptionist </label>
                                                                        </div>
                                                                        <div class="checkbox checkbox-info checkbox-circle">
                                                                            <input id="checkbox-15" type="checkbox">
                                                                            <label for="checkbox-15"> @SmartSchool.Resources.Resource1.Super_Admin </label>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <br />
                                    @if (rol.can_add == 1)
                                    {
                                        <div class="form-group">
                                            <div class="pull-right">
                                                <input type="submit" class="btn btn-info" value="Send" onclick="location.href='@Url.Action("Action", "Admin")'" />
                                            </div>
                                            <div class="pull-left">
                                                <input type="button" class="btn btn-info" value="Back to board" onclick="location.href='@Url.Action("notice_board", "Communicate")'" />
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            }
        }
    }
}