SmartSchool/SmartSchool/Models/role.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int id { get; set; }
        public string roll_name { get; set; }
        public string slug { get; set; }
        public Nullable<int> is_active { get; set; }
        public int is_system { get; set; }
        public int is_superadmin { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public int college_id { get; set; }
        public int branch_id { get; set; }
        public string year { get; set; }
    }
}

SmartSchool/SmartSchool/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartSchool.Models;
using System.Data.Entity.Validation;
using System.Data.Entity.Migrations;
using System.Threading.Tasks;
using System.Net;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SmartSchool.SchoolMasterClasses;
using Newtonsoft.Json;
using SmartSchool.Interfaces;
using static SmartSchool.SchoolMasterClasses.StudentInformation;

namespace SmartSchool.Controllers
{
    public class RolesController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        SmartSchoolHDEntities dbcontext = new SmartSchoolHDEntities();

        private readonly ISessionStore _UsesessionStore;
        public get_session_data1 listData;

        public RolesController(ISessionStore _GetsessionStore)
        {
            try
            {
                _UsesessionStore = _GetsessionStore;
                listData = _UsesessionStore.Get<get_session_data1>("currentSession") as get_session_data1;
                if (listData == null)
                {
                    throw new Exception("Session not been set in RolesController");
                }
            }
            catch (Exception ex)
            {
                ExceptionLogging.LogException(ex);
            }

        }

        // GET: Roles
        public ActionResult Index()
        {
            ViewBag.list = dbcontext.AspNetRoles.Where(k=>k.Id != "dd184641-0108-450d-8f21-68a5d36922f4").ToList();
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.list = dbcontext.AspNetRoles.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                ViewBag.list = context.Roles.ToList();

                context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                int save = context.SaveChanges();
                if (save > 0)
                {
                    TempData["message"] = "Role Created Successfully";
                }

                else
                {
                    TempData["message"] = "Oops..... Somethong Went Wrong.....!!!!";
                }
                return RedirectToAction("Index");
            }
            catch
            {

                return View();
            }
        }
        public ActionResult Edit(string roleName)
        {
            ViewBag.list = dbcontext.AspNetRoles.ToList();
            var thisRole = dbcontext.AspNetRoles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            ViewBag.Role = thisRole;
            ViewBag.pop3 = "1";
            return View("Index");
        }


        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AspNetRole role, string RoleId, string RoleName)
        {
            ViewBag.list = dbcontext.AspNetRoles.ToList();
            try
            {
                var ID = RoleId;
                var idz = dbcontext.AspNetRoles.Where(x => x.Id == ID).Select(a => a.Id).FirstOrDefault();
                AspNetRole asp = dbcontext.AspNetRoles.Find(idz);
                if (asp.Id == idz)
                {
                    asp.Id = asp.Id;
                    asp.Name = RoleName;
                                     
                }

                dbcontext.AspNetRoles.AddOrUpdate(asp);
                int save = dbcontext.SaveChanges();
                if (save > 0)
                {
                    TempData["message"] = "Record edited Successfully!";
                    ModelState.Clear();
                }
                else
                {
                    TempData["message"] = "Please Try Again!";
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(string RoleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            int save = context.SaveChanges();
            if (save > 0)
            {
                TempData["message"] = "Record Deleted Successfully!";
                ModelState.Clear();
            }
            else
            {
                TempData["message"] = "Please Try Again!";
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult AssignRole(string roleid)
        {            
            var user = (from asp in dbcontext.AspNetRoles where asp.Id == roleid select asp.Name).FirstOrDefault();
            if (user == "SuperAdmin")
            {
                nodatainroles();
            }
            else
            {
                ViewBag.getall = (from pg in dbcontext.permission_group
                                  join pc in dbcontext.permission_category on pg.id equals pc.perm_group_id
                                  join pr in dbcontext.roles_permissions on pc.id equals pr.perm_cat_id into nep
                                  from x in nep.DefaultIfEmpty()
                                  where x.college_id == listData.CollegeID && x.year == listData.academic_year && x.branch_id == listData.BranchID && x.role_id == roleid
                                  select new AssignRole
                                  {
                                      id = pg.id,//cat id
                                      name = pg.name,//cat name
                                      Mname = pc.name,//role name
                                      cat_id = pc.id,
                                      can_view = x.can_view == null ? 0 : (int)x.can_view,
                                      can_add = x.can_add == null ? 0 : (int)x.can_add,
                                      can_edit = x.can_edit == null ? 0 : (int)x.can_edit,
                                      can_delete = x.can_delete == null ? 0 : (int)x.can_delete
                                  }).ToList();

                if (ViewBag.getall.Count == 0)
                {
                    nodatainroles();
                }

            }

            return View();
        }


        protected void nodatainroles()
        {
            ViewBag.getall = (from pg in dbcontext.permission_group
                              join pc in dbcontext.permission_category on pg.id equals pc.perm_group_id
                              join pr in dbcontext.roles_permissions on pc.id equals pr.perm_cat_id into nep
                              from x in nep.DefaultIfEmpty()
                              where x.college_id == 0 && x.branch_id == 0 && x.year == listData.academic_year
                              select new AssignRole
                              {
                                  id = pg.id,//cat id
                                  name = pg.name,//cat name
                                  Mname = pc.name,//role name
                                  cat_id = pc.id,
                                  can_view = x.can_view == null ? 0 : (int)x.can_view,
                                  can_add = x.can_add == null ? 0 : (int)x.can_add,
                                  can_edit = x.can_edit == null ? 0 : (int)x.can_edit,
                                  can_delete = x.can_delete == null ? 0 : (int)x.can_delete
                              }).ToList();
        }


        [HttpPost]
        public JsonResult roles_save(List<saveroles> allval, string getpath)
        {
            bool res = false;
            foreach (var items in allval)
            {
                var catid = items.catid;
                var fea = items.get_fea;
                var name = items.modelname;
                var cv = items.get_fun[0];
                var ca = items.get_fun[1];
                var ce = items.get_fun[2];
                var cd = items.get_fun[3];

               res = saveroles(Convert.ToInt32(catid), Convert.ToInt32(cv), Convert.ToInt32(ca), Convert.ToInt32(ce), Convert.ToInt32(cd), getpath);
            }
            if (res == true)
            {
                return Json("Roles Saved Successfully..!", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("Session expired... Please Login Again!", JsonRequestBehavior.AllowGet);
            }
        }
        protected bool saveroles(int catid, int? cv, int? ca, int? ce, int? cd, string aspnetroleid)
        {
            if (listData != null)
            {
                dynamic sesval = Session["sessiondata"];
                roles_permissions pr = new roles_permissions
                {
                    role_id = aspnetroleid,
                    perm_cat_id = catid,
                    can_view = cv,
                    can_add = ca,
                    can_edit = ce,
                    can_delete = cd,
                    created_at = DateTime.Now,
                    college_id = listData.CollegeID,
                    branch_id = listData.BranchID,
                    created_by = listData.user

                };
                dbcontext.roles_permissions.AddOrUpdate(k => new { k.role_id, k.perm_cat_id, k.college_id, k.branch_id }, pr);
                dbcontext.SaveChanges();
                return true;
            }
            else
            {
                return false;
            }
        }

        [HttpPost]
        public ActionResult AssignRole()
        {
            return View();
        }

    }
}

SmartSchool/SmartSchool/Views/Roles/AssignRole.cshtml
@model IEnumerable<SmartSchool.SchoolMasterClasses.AssignRole>

@{
    ViewBag.Title = "AssignRole";
    Layout =  "~/Views/Admin/Shared/_AdminLayoutPage.cshtml";
}

<h2>@SmartSchool.Resources.Resource1.AssignRole</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table" id="tabledata">
    <tr>
        <th>
            @SmartSchool.Resources.Resource1.Model Name
        </th>
        <th>
            @SmartSchool.Resources.Resource1.Features
        </th>
        <th>
            @SmartSchool.Resources.Resource1.View
        </th>
        <th>
            @SmartSchool.Resources.Resource1.Add
        </th>
        <th>
            @SmartSchool.Resources.Resource1.Edit
        </th>
        <th>
            @SmartSchool.Resources.Resource1.Delete
        </th>


    </tr>
    @{
        string groupname = null;
        foreach (var item in ViewBag.getall)
        {
            <tr>
                @if (groupname != item.name)
                {
                    <td>
                        @item.name
                    </td>
                    groupname = item.name;
                }
                else
                {
                    <td></td>
                }

                <td>
                    <input type="hidden" value="@item.Mname" name="catname" />@item.Mname

                    <input type="hidden" value="@item.cat_id" name="id" />
                </td>
                <td>
                    <input type="checkbox" value="0" @(item.can_view == 1 ? "checked" : "") class="checkbox checkbox-info" />
                </td>
                <td>
                    <input type="checkbox" value="1" @(item.can_add == 1 ? "checked" : "") class="checkbox checkbox-info" />
                </td>
                <td>
                    <input type="checkbox" value="1" @(item.can_edit == 1 ? "checked" : "") class="checkbox checkbox-info" />
                </td>
                <td>
                    <input type="checkbox" value="1" @(item.can_delete == 1 ? "checked" : "") class="checkbox checkbox-info" />
                </td>
            </tr>
        }
    }

</table>

<input type="button" id="btnsave" name="Save" title="Save" value="Save" />



<script type="text/javascript">
    var get_features = [];
    var get_functis = [];
    var allval = new Array();
    var mergeVal = {};
    var j = 4;
    $(document).ready(function (e) {
        $('#btnsave').on('click', function () {
            var path = window.location.href.split('=').pop();
            var getpath = path.toString();
            alert(getpath);
            $("#tabledata tbody tr").each(function (i) {
                if (i == 0) {
                }
                else {
                    mergeVal = new Object();
                    get_features = new Array();
                    get_functis = new Array();
                    mergeVal.modelname = $(this).find("td:eq(0)").html();
                    mergeVal.get_fea = ($(this).find("td:eq(1) input[name='catname']").val());
                    mergeVal.catid = ($(this).find("td:eq(1) input[name='id']").val());
                    for (var k = 2; k < 6; k++) {
                        if ($(this).find("td:eq(" + k + ") input[type='checkbox']").is(':checked')) {
                            get_functis.push(1);
                        }
                        else {
                            get_functis.push(0);
                        }
                    }
                    mergeVal.get_fun = get_functis;
                    allval.push(mergeVal);
                }
            });
            $.ajax({
                url: "/Roles/roles_save",
                type: "post",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                async: false,
                data: JSON.stringify({ 'allval': allval, 'getpath': getpath }),
                success: function (response) {
                    $.toast({
                        text: response,
                        position: 'top-right',
                        loaderBg: '#fec107',
                        icon: 'success',
                        hideAfter: 4000,
                        stack: 6
                    });
                },
                error: function (e) {
                    $.toast({
                        text: 'Something Wrong.. Please try Again?',
                        position: 'top-right',
                        loaderBg: '#fec107',
                        icon: 'warning',
                        hideAfter: 4000,
                        stack: 6
                    });
                }
            });
        });
    });
</script>

SmartSchool/SmartSchool/Views/Roles/Index.cshtml
@*@model IEnumerable<SmartHealth_HDSCL.Models.AspNetRole>*@


@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Admin/Shared/_AdminLayoutPage.cshtml";
}
@using SmartSchool.Models;
@using SmartSchool.Interfaces;
@using SmartSchool.SchoolMasterClasses;
@{
    ISessionStore sessionStore = new SessionClass();
    get_session_data1 listData = sessionStore.Get<get_session_data1>("currentSession") as get_session_data1;
    ModulesAccess mm = new ModulesAccess();
    SmartSchoolHDEntities dbcontext = new SmartSchoolHDEntities();

    var getrolesacc = mm.RoleAccess(listData.roleid, 17, 105, listData.CollegeID, listData.BranchID);
    if (getrolesacc != null)
    {
        foreach (var rol in getrolesacc)
        {
            <div class="row">
                <div class="col-md-4">
                    <div class="panel panel-default card-view">
                        <div class="panel-heading">
                            <div class="pull-left">
                                <h2>@SmartSchool.Resources.Resource1.Create New Role</h2>

                            </div>
                        </div>
                        <div class="panel-wrapper collapse in mt-25">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-sm-12 col-xs-12">
                                        <div class="form-wrap">

                                            <div class="form-group">

                                                <div class="input-group">
                                                    @using (Html.BeginForm("Create", "Roles", FormMethod.Post))
                                                    {
                                                        @Html.AntiForgeryToken()
                                                        @Html.ValidationSummary(true)


                                                        <div class="col-md-12">
                                                            <div class="form-group">
                                                                <label class="control-label mb-10" for="exampleInputuname_1">@SmartSchool.Resources.Resource1.Role Name</label>
                                                                @Html.TextBox("RoleName")
                                                            </div>
                                                        </div>


                                                        <div class="col-md-12 col-md-push-2">
                                                            <div class="form-group">
                                                                <input type="submit" class="btn btn-success mr-10 mt-10" value="Create" />
                                                                <button type="submit" class="btn btn-default mt-10">@SmartSchool.Resources.Resource1.Cancel</button>

                                                            </div>
                                                        </div>

                                                    }
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-8">
                    <div class="panel panel-default card-view">
                        <div class="panel-heading">
                            <div class="pull-left">
                                <h2>@SmartSchool.Resources.Resource1.Created Roles</h2>

                            </div>

                        </div>
                        <div class="panel-wrapper collapse in">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-sm-12 col-xs-12">
                                        <div class="form-wrap">


                                            <div class="panel-body">

                                                <center>
                                                    <table class="table table-striped m-b-0">
                                                        <tr>
                                                            <th>
                                                                @SmartSchool.Resources.Resource1.Role
                                                            </th>
                                                            <th>@SmartSchool.Resources.Resource1.Action</th>


                                                        </tr>
                                                        @foreach (var role in ViewBag.list)
                                                        {
                                                            <tr>
                                                                <td>
                                                                    @role.Name
                                                                </td>
                                                                <td>
                                                                    <span class="label label-table label-success"> @Html.ActionLink("Edit", "Edit", new { roleName = @role.Name })</span>|
                                                                    <span onclick="return confirm('Are you sure to delete?')"><a href="/Roles/Delete?RoleName=@role.Name" class="delLink label label-table label-danger" style="color:white;">@SmartSchool.Resources.Resource1.Delete</a></span>|
                                                                    <span class="label label-table label-success"> @Html.ActionLink("AssignRole", "AssignRole", new { roleid = @role.Id })</span>
                                                                </td>
                                                            </tr>
                                                        }
                                                    </table>
                                                </center>

                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>





            </div>



            if (ViewBag.Role != null)
            {

                <div id="responsive-modal3" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: block;" data-backdrop="static" data-keyboard="false">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h5 class="modal-title">@SmartSchool.Resources.Resource1.Edit Role</h5>
                            </div>
                            <div class="modal-body">
                                @using (Html.BeginForm("Edit", "Roles", FormMethod.Post, new { RoleId = "RoleId", RoleName = "RoleName", enctype = "multipart/form-data" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <div class="form-body">
                                        <div class="form-horizontal">
                                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        @Html.Label("@SmartSchool.Resources.Resource1.Role ID", htmlAttributes: new { @class = "control-label pl-15" })
                                                        <div class="col-md-12">
                                                            <input type="text" id="RoleId" name="RoleId" value="@(ViewBag.Role.Id ?? String.Empty)" class="form-control" readonly />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        @Html.Label("@SmartSchool.Resources.Resource1.Role Name", htmlAttributes: new { @class = "control-label pl-15" })
                                                        <div class="col-md-12">
                                                            <input type="text" id="RoleName" name="RoleName" value="@(ViewBag.Role.Name ?? String.Empty)" class="form-control" />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            @if (rol.can_add == 1)
                                            {
                                                <div class="row">

                                                    <div class="row">
                                                        <div class="form-actions mt-10 col-md-6">
                                                            <button type="submit" class="btn btn-success  mr-10" id="btnsubtimeline"> Save</button>
                                                            <button type="button" class="btn btn-default clr" data-dismiss="modal">Cancel</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            }
                                        </div>
                                    </div>

                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    }
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>




<script type="text/javascript">
    $(document).ready(function () {
        //$("#responsive-modal2").hide();
        $("#EditRole").click(function () {
            $("#responsive-modal3").show();
        });

        $('.close').click(function () {

            $("#responsive-modal3").hide();
            window.location.href = '../../Roles/Index';

        });
    });

</script>

@if (ViewBag.pop3 != null)
{
    string pop = ViewBag.pop3;
    string p = "1";
    if (p.Equals(pop))
    {
        <script type="text/javascript">
            window.onload = function () {
                $("#responsive-modal3").show();
            }
            $('.close').click(function () {

                $("#responsive-modal3").hide();
                window.location.href = '../../Roles/Index';

            });
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.onload = function () {
                $("#responsive-modal3").hide();
            }
        </script>
    }
}
@if (TempData["message"] != null)
{
    <script type="text/javascript">
        $(document).ready(function () {
            var tempdata = '@TempData["message"]';

            $.toast({
                //heading: '2 new messages',
                text: tempdata,
                     position: 'top-right',
                     loaderBg: '#fec107',
                     icon: 'warning',
                     hideAfter: 3500,
                     stack: 6
                 });


        });
    </script>
}