SmartSchool/SmartSchool/Models/homework.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class homework
    {
        public int id { get; set; }
        public int class_id { get; set; }
        public int section_id { get; set; }
        public Nullable<System.DateTime> homework_date { get; set; }
        public Nullable<System.DateTime> submit_date { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<int> subject_id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string document { get; set; }
        public Nullable<int> evaluated_by { get; set; }
        public Nullable<int> college_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string year { get; set; }
        public Nullable<System.DateTime> modified_dt { get; set; }
    }
}

SmartSchool/SmartSchool/Controllers/HomeWorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using SmartSchool.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity.Migrations;
using System.Web.UI.WebControls;
using System.Net;
using SmartSchool.SchoolMasterClasses;
using System.IO;
using System.Threading.Tasks;
using SmartSchool.Interfaces;
using System.Text.RegularExpressions;
using static SmartSchool.SchoolMasterClasses.StudentInformation;

namespace SmartSchool.Controllers
{
    public class HomeWorkController : Controller
    {
        // GET: HomeWork
        public SmartSchoolHDEntities dbContext = new SmartSchoolHDEntities();
        public get_staff_classes gs = new get_staff_classes();
        public custom_master_class cmc = new custom_master_class();
        SmsTextLocalClass SMSClass = new SmsTextLocalClass();
        private readonly ISessionStore _UsesessionStore;
        public get_session_data1 listData;
        public HomeWorkController(ISessionStore _GetsessionStore)
        {
            try
            {
                _UsesessionStore = _GetsessionStore;
                listData = _UsesessionStore.Get<get_session_data1>("currentSession") as get_session_data1;
                if (listData == null)
                {
                    throw new Exception("Session not been set in AdminController");
                }
            }
            catch (Exception ex)
            {
                ExceptionLogging.LogException(ex);
            }
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult callgetsec(int? ddlclass)
        {
            var result = gs.get_staff_wise_classes(ddlclass, listData.CollegeID, listData.BranchID, listData.academic_year, listData.roleid);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult student_attendance()
        {
            var getstaffdata = gs.get_staff_wise_classes(0, listData.CollegeID, listData.BranchID, listData.academic_year,  listData.roleid);
            IQueryable<AddClass> iq = dbContext.AddClasses;
            List<SelectListItem> lc = new List<SelectListItem>();
            foreach (var group in getstaffdata)
            {
                int clsid = Convert.ToInt32(group.class_id);
                lc.Add(iq.OrderBy(a => a.class_name).Where(k => k.class_id == clsid).Select(b => new SelectListItem { Value = b.class_id.ToString(), Text = b.class_name }).Distinct().FirstOrDefault());
            }
            ViewBag.cls = lc;
            return View();
        }
        [HttpPost]
        public JsonResult callgetsecsub(int? ddlclass, int? ddlsection)
        {
            int? stafid = gs.getStaffId(listData.CollegeID, listData.BranchID, listData.academic_year);
            List<SelectListItem> selectLists = new List<SelectListItem>();
            var result = dbContext.getSubjects(listData.CollegeID, listData.BranchID, stafid, ddlclass, ddlsection, listData.academic_year, listData.roleid).ToList();

            foreach (var re in result)
            {
                selectLists.Add(new SelectListItem
                {
                    Text = re.name,
                    Value = re.id.ToString()
                });
            }
            SelectListItem st = new SelectListItem()
            {
                Text = "Select",
                Value = "0"
            };
            selectLists.Insert(0, st);
            return Json(selectLists, JsonRequestBehavior.AllowGet);
        }
      
        private void bind_class_rooms()
        {
            var userlist = gs.getClass(listData.CollegeID, listData.BranchID, listData.academic_year, listData.roleid);
            ViewBag.cls = userlist;
        }

        [HttpGet]
        public ActionResult evaluation_report()
        {
            bind_class_rooms();
            ViewBag.GetEvaluationReport = homeworkEvaluationData(null);
            return View();
        }

        private List<evaluation_report> homeworkEvaluationData(int? homeworkid)
        {
            int i = 0;
            List<evaluation_report> modalevaluation = new List<evaluation_report>();
            if (homeworkid > 0)
            {
                modalevaluation = dbContext.Pro_GHWER(listData.CollegeID, listData.BranchID, listData.academic_year, homeworkid).Select(k => new evaluation_report {
                    homework_id = k.homework_id,
                    FirstName = k.firstname,
                    LastName = k.lastname,
                    stringDate = k.stringDate,
                    class_id  = k.class_id,
                    section_id = k.section_id,
                    name = k.name,
                    admission_no = k.admission_no,
                    Description = k.Description,
                    Assigned_By = k.Assigned_by,
                    Evaluated_by = k.Evaluated_by,
                    homework_date = k.homework_date,
                    submit_date = k.submit_date,
                    class_name = k.class_name,
                    Section = k.section,
                    created_by = k.created_by

                }).ToList();
            }
            else
            {
                modalevaluation = (from a in dbContext.homework
                                   join b in dbContext.homework_evaluation on a.id equals b.homework_id into leftjoin
                                   from lj in leftjoin.DefaultIfEmpty()
                                   join c in dbContext.subjects on a.subject_id equals c.id
                                   join d in dbContext.staffs on a.evaluated_by equals d.id into leftjoinstaff
                                   from ljs in leftjoinstaff.DefaultIfEmpty()
                                   where a.college_id == listData.CollegeID && a.branch_id == listData.BranchID && a.year == listData.academic_year
                                   group new { a, lj, c, ljs } by new { lj.homework_id, a.class_id, a.section_id, ljs.name }
                            into gr

                                   select new SchoolMasterClasses.evaluation_report
                                   {
                                       name = gr.Select(k => k.c.name).FirstOrDefault(),
                                       homework_date = gr.Select(k => k.a.homework_date).FirstOrDefault(),
                                       date = gr.Select(k => k.lj.date).FirstOrDefault(),
                                       Evaluated_by = gr.Select(k => k.ljs.name).FirstOrDefault() == null ? "Evaluation Pending Yet." : gr.Select(k => k.ljs.name).FirstOrDefault(),
                                       submit_date = gr.Select(k => k.a.submit_date).FirstOrDefault(),
                                       StudCount = gr.Select(k => k.lj.homework_id).FirstOrDefault() == 0 ? 0 : gr.Count(),
                                       class_id = gr.Select(k => k.a.class_id).FirstOrDefault(),
                                       section_id = gr.Select(k => k.a.section_id).FirstOrDefault(),
                                       subject_id = gr.Select(k=>k.c.id).FirstOrDefault(),
                                       id = gr.Select(k => k.a.id).FirstOrDefault(),

                                   }).ToList();

                foreach (var me in modalevaluation)
                {
                    int? total_students = dbContext.students.Where(k => k.class_id == me.class_id && k.section_id == me.section_id && k.college_id == listData.CollegeID && k.branch_id == listData.BranchID && k.year == listData.academic_year).Select(k => k.id).Count();
                    int? get_pending_students = (total_students - me.StudCount);
                    modalevaluation[i].PendingStudCount = get_pending_students;
                    int? evaluatedStudCount = me.StudCount;
                    double? percentages = ((double)evaluatedStudCount / (double)total_students) * 100;
                    modalevaluation[i].percentage = (int)Math.Ceiling((double)percentages);
                    i++;
                }
            }
            return modalevaluation;
        }

        public ActionResult getHomeworkEvalutionDataById(int id)
        {
            ModelState.Clear();
            List<evaluation_report> ler = homeworkEvaluationData(id).ToList();
            return PartialView(ler);
        }

        [HttpPost]
        public ActionResult evaluation_report(Models.homework HMevaluation, int? class_id, int? section_id, int? subject_id)
        {
            bind_class_rooms();
            ViewBag.GetEvaluationReport = homeworkEvaluationData(null).Where(k => k.class_id == class_id && k.section_id == section_id && k.subject_id == subject_id).ToList();
            ViewBag.sectionid = section_id;
            ViewBag.subjectid = subject_id;
            return View();
        }

        [HttpGet]
        public ActionResult Editevaluation_report(int? Id)
        {
            var data = dbContext.homework_evaluation.Where(a => a.id == Id).Select(pp => pp).FirstOrDefault();
            return View(data);
        }

        [HttpPost]
        public ActionResult Editevaluation_report(homework_evaluation HMevaluation, int? Id)
        {
            var data = dbContext.homework_evaluation.Where(a => a.id == Id).Select(pp => pp).FirstOrDefault();
            if (data.id == HMevaluation.id)
            {
                data.homework_id = HMevaluation.homework_id;
                data.student_id = HMevaluation.student_id;
                data.date = HMevaluation.date;
                data.status = HMevaluation.status;
                data.college_id = HMevaluation.college_id;
                data.branch_id = HMevaluation.branch_id;
                data.created_by = HMevaluation.created_by;

SmartSchool/SmartSchool/Views/HomeWork/DeleteHomework.cshtml
@model SmartSchool.Models.homework

@{
    ViewBag.Title = "DeleteHomework";
    Layout = "~/Views/Admin/Shared/_AdminLayoutPage.cshtml";
}

<h2>@SmartSchool.Resources.Resource1.Delete_Homework</h2>

<h3>@SmartSchool.Resources.Resource1.Are_you_sure_you_want_to_delete_this_?</h3>
<div>
    <h4>@SmartSchool.Resources.Resource1.Homework</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.class_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.class_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.section_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.section_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.homework_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.homework_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.submit_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.submit_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.staff_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staff_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.subject_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subject_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.create_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.create_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.document)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.document)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.evaluated_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evaluated_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.college_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.college_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.branch_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.branch_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modified_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modified_by)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SmartSchool/SmartSchool/Views/HomeWork/Deleteevaluation_report.cshtml
@model SmartSchool.Models.homework_evaluation

@{
    ViewBag.Title = "Deleteevaluation_report";
    Layout = "~/Views/Admin/Shared/_AdminLayoutPage.cshtml";
}


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h4 style="color:#f742aa; ">@SmartSchool.Resources.Resource1.homework_evaluation</h4>
                </div>               
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<h3>@SmartSchool.Resources.Resource1.Are_you_sure_you_want_to_delete_this_?</h3>
<div>
    <h4>@SmartSchool.Resources.Resource1.Delete_evaluation_report</h4>
    <div class="panel panel-default card-view">
        <div class="panel-wrapper collapse in">
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <div class="form-wrap">
                            <div class="form-body">
                                <hr />
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.homework_id)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.homework_id)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.student_id)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.student_id)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.date)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.date)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.status)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.status)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.college_id)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.college_id)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.branch_id)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.branch_id)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.created_by)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.created_by)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.modified_by)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.modified_by)
                                    </dd>

                                </dl>

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-actions no-color">
                                        <input type="submit" value="Delete" class="btn btn-default" /> |
                                        @Html.ActionLink("Back to List", "evaluation_report")
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>           

SmartSchool/SmartSchool/Views/HomeWork/EditHomework.cshtml
@model SmartSchool.Models.homework

@{
    ViewBag.Title = "add_homework";
    Layout = "~/Views/Admin/Shared/_AdminLayoutPage.cshtml";
}
@{
    <script type="text/javascript">
        $(window).on('load', function () {
            $('#myModal').modal('show');
        });

/**/</script>
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h4 style="color:#f742aa; ">@SmartSchool.Resources.Resource1.Homework</h4>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("EditHomework", "HomeWork", FormMethod.Post, new { FileUpload = "FileUpload", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content modal-media-content">

                    <div class="modal-header  modal-media-header">
                        <h4 class="box-title"><i class="zmdi zmdi-local-library mr-10">@SmartSchool.Resources.Resource1.Edit_Home_Work</i></h4>
                        <button type="button" class="close" data-dismiss="modal" onclick="window.location.href='/Homework/add_homework'">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="modal-body pt0 pb0">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 paddlr">
                                    <form id="formadd" method="post" class="ptt10" enctype="multipart/form-data">
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <div class="form-group">
                                                        @Html.Label(@SmartSchool.Resources.Resource1.Class, htmlAttributes: new { @class = "control-label col-md-4" })
                                                        <span style="color:red">*</span>
                                                        <div class="col-sm-10">
                                                            @Html.DropDownList("class_id", new SelectList(ViewBag.cls, "Value","Text"), "Select", new { @class = "form-control", @required = "requied", id = "class_id" })
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="form-group">
                                                        @Html.Label(@SmartSchool.Resources.Resource1.Section, htmlAttributes: new { @class = "control-label col-md-4" })
                                                        <span style="color:red">*</span>
                                                        <div class="col-sm-10">
                                                            @Html.DropDownList("section_id", new SelectList(string.Empty, "Value", "Text"), new { @class = "form-control", required = "required", id = "section_id" })
                                                        </div>
                                                    </div>
                                                </div>


                                                <div class="col-sm-4">
                                                    <div class="form-group">
                                                        @Html.Label(@SmartSchool.Resources.Resource1.Subject, htmlAttributes: new { @class = "control-label col-md-4" })
                                                        <span style="color:red">*</span>
                                                        <div class="col-sm-10">
                                                            @Html.DropDownList("subject_id", new SelectList(string.Empty, "Value", "Text"), new { @class = "form-control", @required = "required", id = "subject_id1" })
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <br />
                                            <br />
                                            <div class="col-sm-4">
                                                <div class="form-group">
                                                    <label for="pwd">@SmartSchool.Resources.Resource1.HomeWorkDate</label>
                                                    <span style="color:red">*</span>
                                                    @Html.EditorFor(model => model.homework_date, new { htmlAttributes = new { @class = "form-control", type = "date", id = "from", @required = "required" } })
                                                </div>
                                            </div>

                                            <div class="col-sm-4">
                                                <div class="form-group">
                                                    <label for="pwd">@SmartSchool.Resources.Resource1.SubmissionDate</label>
                                                    <span style="color:red">*</span>
                                                    @Html.EditorFor(model => model.submit_date, new { htmlAttributes = new { @class = "form-control", type = "date", id = "to", @required = "required" } })
                                                </div>
                                            </div>
                                            <div class="col-sm-3">
                                                <div class="form-group">
                                                    <label for="pwd">@SmartSchool.Resources.Resource1.Attach_Document</label>
                                                    <input type="file" id="FileUpload" name="FileUpload" />

                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-4" })
                                                <div class="col-md-10">
                                                    @Html.TextAreaFor(model => model.description, new { @class = "tinymce", type = "textarea", format = "text" })

                                                </div>
                                            </div>
                                        </div>
                                        <!-- Modal footer -->
                                        <div class="modal-footer">
                                            <div class="pull-right paddA10">
                                                <input type="submit" class="btn btn-primary pull-right btn-sm" value="Save">
                                            </div>
                                        </div>
                                        <!--./row-->
                                    </form>
                                </div><!--./col-md-12-->
                            </div><!--./row-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#section_id').on('change', function () {
            var ddlsection = $(this).val();
            var ddlclass = $('#class_id').val();
            $('#subject_id1').empty();
            $.ajax({
                method: 'POST',
                url: '/HomeWork/callgetsecsub',
                contentType: "application/json; charset=utf-8",
                datatype: "Json",
                data: JSON.stringify({ 'ddlclass': ddlclass, 'ddlsection': ddlsection }),
                success: function (data) {
                    $.each(data, function (i) {
                        if (i == "Disabled") {
                            $("#subject_id1").append("<option value='" + data.Value + "'>" + data.Text + "</option > ");
                        }
                        else {
                            $("#subject_id1").append("<option value='" + data[i].Value + "'>" + data[i].Text + "</option > ");
                        }
                    });
                }
            });
        });
    });
</script>

<script>
    $('#class_id').on('change', function () {
        var ddlclass = $(this).val();
        $('#section_id').empty();
        $('#subject_id').empty();
        $("#section_id").html("<option value=''>Select Section</option>");
        $.ajax({
            method: 'POST',
            url: '/HomeWork/callgetsec',
            contentType: "application/json; charset=utf-8",
            datatype: "Json",
            data: JSON.stringify({ 'ddlclass': ddlclass }),
            success: function (data) {
                $.each(data, function (i) {
                    if (i == "Disabled") {
                        $("#section_id").append("<option value='" + data.Value + "'>" + data.Text + "</option > ");
                    }
                    else {
                        $("#section_id").append("<option value='" + data[i].Value + "'>" + data[i].Text + "</option > ");
                    }

                });
            }
        });
    });
</script>