SmartSchool/SmartSchool/Models/AddClass.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddClass()
        {
            this.class_subjects = new HashSet<class_subjects>();
            this.class_sections = new HashSet<class_sections>();
            this.class_teacher = new HashSet<class_teacher>();
        }
    
        public int class_id { get; set; }
        public string class_name { get; set; }
        public Nullable<int> college_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public string year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<class_subjects> class_subjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<class_sections> class_sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<class_teacher> class_teacher { get; set; }
    }
}

SmartSchool/SmartSchool/Controllers/AcademicsController.cs
using System.Web.Mvc;
using System.Data;
using System.Data.Entity.Migrations;
using System.Linq;
using System;
using System.Net;
using SmartSchool.Models;
using SmartSchool.SchoolMasterClasses;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using SmartSchool.Interfaces;
using static SmartSchool.SchoolMasterClasses.StudentInformation;

namespace SmartSchool.Controllers
{
    public class AcademicsController : Controller
    {
        public SmartSchoolHDEntities dbContext = new SmartSchoolHDEntities();
        public custom_master_class cmc = new custom_master_class();
        public get_staff_classes gs = new get_staff_classes();

        private readonly ISessionStore _UsesessionStore;
        public get_session_data1 listData;
        public AcademicsController(ISessionStore _GetsessionStore)
        {
            try
            {
                _UsesessionStore = _GetsessionStore;
                listData = _UsesessionStore.Get<get_session_data1>("currentSession") as get_session_data1;
                if (listData == null)
                {
                    throw new Exception("Session not been set in AdminController");
                }
            }
            catch (Exception ex)
            {
                ExceptionLogging.LogException(ex);
            }
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ClassTimetable()
        {
            bind_section();
            GetClassSection(null);
            return View();
        }

        public void bind_Add_clas()
        {
            var u_lists = dbContext.AddClasses.Where(cs => cs.college_id == listData.CollegeID && cs.branch_id == listData.BranchID && cs.year == listData.academic_year).OrderBy(a => a.class_name).ToList().Select(b => new SelectListItem { Value = b.class_id.ToString(), Text = b.class_name.ToString() }).ToList();
            ViewBag.addcls = u_lists;
        }

        public void bind_section()
        {
            var u_list = dbContext.sections.Where(cs => cs.college_id == listData.CollegeID && cs.branch_id == listData.BranchID && cs.year == listData.academic_year).OrderBy(a => a.id).ToList().Select(b => new SelectListItem { Value = b.id.ToString(), Text = b.section1.ToString() }).ToList();
            ViewBag.clas1 = u_list;
        }

        [HttpGet]
        public ActionResult GetClassSection(int? classid)
        {
            ViewBag.cls = gs.getClass(listData.CollegeID, listData.BranchID, listData.academic_year, listData.roleid);
            ViewBag.sections = gs.get_staff_wise_classes(classid, listData.CollegeID, listData.BranchID, listData.academic_year, listData.roleid);
            return View();
        }


        public void bind_Subject()
        {
            List<subject> c = dbContext.subjects.Where(x => x.id != 0 && x.college_id == listData.CollegeID && x.branch_id == listData.BranchID && x.year == listData.academic_year).ToList();
            subject sub = new subject
            {
                name = " select subject Name",
                id = 0
            };
            c.Insert(0, sub);
            SelectList u_list = new SelectList(c, "id", "name ", 0);
            ViewBag.clas11 = u_list;
        }

        [HttpGet]
        public ActionResult student_attendance()
        {
            var getstaffdata = gs.get_staff_wise_classes(0, listData.CollegeID, listData.BranchID, listData.academic_year,  listData.roleid);
            IQueryable<AddClass> iq = dbContext.AddClasses;
            List<SelectListItem> lc = new List<SelectListItem>();
            foreach (var group in getstaffdata)
            {
                int clsid = Convert.ToInt32(group.class_id);
                lc.Add(iq.OrderBy(a => a.class_name).Where(k => k.class_id == clsid).Select(b => new SelectListItem { Value = b.class_id.ToString(), Text = b.class_name }).Distinct().FirstOrDefault());
            }
            ViewBag.cls = lc;
            return View();
        }

        [HttpPost]
        public JsonResult callgetsec(int? ddlclass)
        {
            var getstaffdata = gs.get_staff_wise_classes(ddlclass, listData.CollegeID, listData.BranchID, listData.academic_year,  listData.roleid);          
            return Json(getstaffdata, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult getTeacher(int? ddlsection, int? ddlclass)
        {
            var teacherdata = gs.getteacher(ddlclass, ddlsection, listData.CollegeID, listData.BranchID, listData.academic_year, listData.roleid);
            return Json(teacherdata, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult getTeacherSubjects(int? ddlsection, int? ddlclass, int? ddlstafid)
        {
            int? stafid = gs.getStaffId(listData.CollegeID, listData.BranchID, listData.academic_year);
            List<SelectListItem> selectLists = new List<SelectListItem>();
            var result = dbContext.getSubjects(listData.CollegeID, listData.BranchID, stafid, ddlclass, ddlsection, listData.academic_year, listData.roleid).ToList();

            foreach (var re in result)
            {
                selectLists.Add(new SelectListItem
                {
                    Text = re.name,
                    Value = re.id.ToString()
                });
            }
            //SelectListItem st = new SelectListItem()
            //{
            //    Text = "Select",
            //    Value = "0"
            //};
            //selectLists.Insert(0, st);
            return Json(selectLists, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult AddClassTimetable(subject model, int? class_ids)
        {
            bind_Add_clas();
            GetClassSection(null);
            student_attendance();
            if (class_ids != null)
            {
                var getvaltt1 = (from a in dbContext.timetables
                                 join b in dbContext.teacher_subjects on a.teacher_subject_id equals b.id
                                 join c in dbContext.subjects on b.subject_id equals c.id
                                 join d in dbContext.class_sections on b.class_section_id equals d.id
                                 join e in dbContext.AddClasses on d.class_id equals e.class_id
                                 where d.class_id == class_ids && a.college_id == listData.CollegeID && a.college_id == listData.BranchID && a.year == listData.academic_year
                                 select new SchoolMasterClasses.timetables
                                 {
                                     classes = e.class_name,
                                     name = c.name,
                                     day_name = a.day_name,
                                     start_time = a.start_time,
                                     end_time = a.end_time,
                                     room_no = a.room_no
                                 }).ToList();

                ViewBag.Gettimetable = getvaltt1;
                ViewBag.getname = getvaltt1.Select(a => a.name).Distinct().ToList();
                ViewBag.cls_id = getvaltt1.Select(a => a.classes).Distinct().ToList();
                var s = ViewBag.cls_id;
                return View();
            }
            var getvaltt = (from a in dbContext.timetables
                            join b in dbContext.teacher_subjects on a.teacher_subject_id equals b.id
                            join c in dbContext.subjects on b.subject_id equals c.id
                            join d in dbContext.class_sections on b.class_section_id equals d.id
                            where a.college_id == listData.CollegeID && a.college_id == listData.BranchID && a.year == listData.academic_year
                            select new SchoolMasterClasses.timetables
                            {
                                name = c.name,
                                day_name = a.day_name,
                                start_time = a.start_time,
                                end_time = a.end_time,
                                room_no = a.room_no
                            }).ToList();

            ViewBag.Gettimetable = getvaltt;
            ViewBag.getname = getvaltt.Select(a => a.name).Distinct().ToList();
            ViewBag.cls_id = class_ids;
            return View();
        }

        [HttpPost]
        public JsonResult AddClassTimetable(string ddlsub, List<timetable> allval, int? ddlcls, int? ddlsec)
        {
            student_attendance();
            bind_Subject();
            if (ddlsub != "" & ddlsec != null & ddlcls != null)
            {
                var subid = (from a in dbContext.teacher_subjects
                             join b in dbContext.class_sections on a.class_section_id equals b.id
                             where a.subject_id.ToString() == ddlsub && b.class_id == ddlcls && b.section_id == ddlsec && a.college_id == listData.CollegeID && a.branch_id == listData.BranchID && a.year == listData.academic_year
                             select a.id).FirstOrDefault();
                int succ = 0;
                if (allval != null)
                {
                    foreach (var alval in allval)
                    {
                        if (alval.start_time != "" && alval.end_time != "" && alval.room_no != "")
                        {
                            //var removetags = Regex.Replace(alval.day_name, "\n", String.Empty).Trim();
                            timetable tt = new timetable()
                            {
                                day_name = alval.day_name,
                                start_time = alval.start_time,
                                end_time = alval.end_time,
                                room_no = alval.room_no,
                                college_id = listData.CollegeID,

SmartSchool/SmartSchool/Views/Academics/AddSection.cshtml
@model SmartSchool.Models.section
@{
    ViewBag.Title = "AddSection";
    Layout = "~/Views/Admin/Shared/_AdminLayoutPage.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h4 style="color:#f742aa; ">@SmartSchool.Resources.Resource1.Academics</h4>
                </div>
                @*<div class="pull-right">
                        <input type="button" class="btn btn-info" value="Add" onclick="location.href='@Url.Action("AddClassTimetable.cshtml", "Admin")'" />
                    </div>*@
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
@using SmartSchool.Models;
@using SmartSchool.Interfaces;
@using SmartSchool.SchoolMasterClasses;
@{
    ISessionStore sessionStore = new SessionClass();
    get_session_data1 listData = sessionStore.Get<get_session_data1>("currentSession") as get_session_data1;
    ModulesAccess mm = new ModulesAccess();
    SmartSchoolHDEntities dbcontext = new SmartSchoolHDEntities();

    var getrolesacc = mm.RoleAccess(listData.roleid, 8, 47, listData.CollegeID, listData.BranchID);
    if (getrolesacc != null)
    {
        foreach (var rol in getrolesacc)
        {

            using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="panel panel-default card-view">
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-12 col-xs-12">
                                    <div class="form-wrap">
                                        <div class="form-body">
                                            <h6 class="txt-dark capitalize-font"><i class="fa fa-plus-square mr-10"></i>@SmartSchool.Resources.Resource1.Add_Section</h6>
                                            <hr class="light-grey-hr" />
                                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })                               
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    @Html.Label("@SmartSchool.Resources.Resource1.Section_Name", htmlAttributes: new { @class = "control-label col-md-4" })
                                                    <span class="txt-danger">*</span>
                                                    <div class="col-md-10">
                                                        @Html.EditorFor(model => model.section1, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                                        @Html.ValidationMessageFor(model => model.section1, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>
                                            </div>                                          
                                        </div>
                                        <br />
                                        <br>
                                        <br />
                                        @if (rol.can_add == 1)
                                        {
                                            <div class="for ==1m-group">
                                                <div class="pull-right">
                                                    <input type="submit" class="btn btn-info" value="Save" />
                                                </div>
                                            </div>

                                        }

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default card-view">
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-12 col-xs-12">
                                    <div class="form-wrap">
                                        <div class="form-body">
                                            <h6 class="txt-dark capitalize-font"><i class="fa fa-list mr-10"></i>@SmartSchool.Resources.Resource1.Section_List</h6>
                                            <hr class="light-grey-hr" />
                                            <div class="table-wrap">
                                                <div class="table-responsive">
                                                    <div id="example_wrapper" class="dataTables_wrapper">
                                                        <table id="example" class="table table-hover display pb-30">
                                                            <thead>
                                                                <tr>
                                                                    <th>
                                                                        @SmartSchool.Resources.Resource1.Section
                                                                    </th>
                                                                    <th>
                                                                        @SmartSchool.Resources.Resource1.Action
                                                                    </th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                @foreach (var item in ViewBag.sectiondata)
                                                                {
                                                                    <tr>
                                                                        <td>
                                                                            @item.section1
                                                                        </td>
                                                                        <td class="form-group">
                                                                            <a href="@Url.Action("UpdateSection", "Academics", new { Id = @item.id })"><span class="zmdi zmdi-edit txt-warning"></span></a>

                                                                            @if (rol.can_delete == 1)
                                                                            {
                                                                                @*<a href="@Url.Action("DeleteSection", "Academics", new { Id = @item.id })"><span class="zmdi zmdi-delete txt-danger"></span></a>*@
                                                                                @Html.ActionLink("   ", "DeleteSection", new { Id = @item.id }, new { @class = "text-inverse zmdi zmdi-delete txt-danger", onclick = "return confirm('Are sure wants to delete?');" })
                                                                            }
                                                                        </td>
                                                                    </tr>

                                                                }
                                                            </tbody>
                                                        </table>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    }
}

SmartSchool/SmartSchool/Views/Academics/Add_class.cshtml
@model SmartSchool.Models.AddClass

@{
    ViewBag.Title = "Add_class";
    Layout = "~/Views/Admin/Shared/_AdminLayoutPage.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h4 style="color:#f742aa; ">@SmartSchool.Resources.Resource1.Academics</h4>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
@using SmartSchool.Models;
@using SmartSchool.Interfaces;
@using SmartSchool.SchoolMasterClasses;
@{
    ISessionStore sessionStore = new SessionClass();
    get_session_data1 listData = sessionStore.Get<get_session_data1>("currentSession") as get_session_data1;
    ModulesAccess mm = new ModulesAccess();
    SmartSchoolHDEntities dbcontext = new SmartSchoolHDEntities();

    var getrolesacc = mm.RoleAccess(listData.roleid, 1, 1, listData.CollegeID, listData.BranchID);
    if (getrolesacc != null)
    {
        foreach (var rol in getrolesacc)
        {
            using (Html.BeginForm("Add_class", "Academics", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="panel panel-default card-view">
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-12 col-xs-12">
                                    <div class="form-wrap">
                                        <div class="form-body">
                                            <div class="form-horizontal">
                                                <h6 class="txt-dark capitalize-font"><i class="fa fa-plus-square mr-10"></i>@SmartSchool.Resources.Resource1.AddClass</h6>
                                                <hr />
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            @Html.Label(@SmartSchool.Resources.Resource1.ClassName, htmlAttributes: new { @class = "control-label col-md-3" })
                                                            <div class="col-md-8">
                                                                @Html.EditorFor(model => model.class_name, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                                                @Html.ValidationMessageFor(model => model.class_name, "", new { @class = "text-danger" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                @if (rol.can_add == 1)
                                                {
                                                    <div class="form-group">
                                                        <div class="col-md-2 ">
                                                            <div class="pull-left">
                                                                <input type="submit" value="Save" class="btn btn-info" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <div class="panel panel-default card-view">
                <div class="panel-wrapper collapse in">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-12 col-xs-12">
                                <div class="form-wrap">
                                    <div class="form-body">
                                        <div class="table-wrap">
                                            <div class="table-responsive">
                                                <h6 class="txt-dark capitalize-font"><i class="fa fa-list mr-10"></i>@SmartSchool.Resources.Resource1.Class_List</h6>
                                                <hr />
                                                <table id="example" class="table table-hover display  pb-30">
                                                    <thead>
                                                        <tr>
                                                            <th>@SmartSchool.Resources.Resource1.ClassName</th>
                                                            @*<th>Action</th>*@
                                                        </tr>
                                                    </thead>
                                                    <tbody>

                                                        @if (ViewBag.getclassname != null)
                                                        {
                                                            foreach (var item in ViewBag.getclassname)
                                                            {
                                                                <tr>
                                                                    <td>@item.class_name</td>
                                                                </tr>
                                                            }
                                                        }
                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
}

SmartSchool/SmartSchool/Views/Academics/EditSubject.cshtml
@model SmartSchool.Models.subject

@{
    ViewBag.Title = "EditSubject";
    Layout = "~/Views/Admin/Shared/_AdminLayoutPage.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default card-view">
            <div class="panel-heading">
                <div class="pull-left">
                    <h4 style="color:#f742aa; ">Academics</h4>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default card-view">
        <div class="panel-wrapper collapse in">
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <div class="form-wrap">
                            <div class="form-body">
                                <div class="form-horizontal">
                                    <h4>subject</h4>
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.id)

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.DropDownList("Subject_id", (IEnumerable<SelectListItem>)ViewBag.clas11, " -- Select Subject --", new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @*@Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })*@
                                            @Html.DropDownListFor(model => model.type, new SelectList(new[]{"--Select Type--",
"Theory", "Practicle"}), new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
                                        </div>
                                    </div>                                   
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Save" class="btn btn-info" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "addSubject")
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
@if (TempData["message"] != null)
{
    <script type="text/javascript">
        $(document).ready(function () {
            var tempdata = '@TempData["message"]';

            $.toast({
                //heading: '2 new messages',
                text: tempdata,
                     position: 'top-right',
                     loaderBg: '#fec107',
                     icon: 'warning',
                     hideAfter: 3500,
                     stack: 6
                 });


        });
    </script>
}